name: Helm update index

on:
  push:
    paths: ['**.tgz']

jobs:
  helm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: azure/setup-helm@v3
        with:
          version: "v3.10.0"

      - name: Helm | Update index
        run: |
          helm repo index .
          git config --global user.email "no-reply@kubees.io"
          git config --global user.name "KubeesBot"
          git add index.yaml
          git commit -m "chore: update chart index"
          git push
